theme: jekyll-theme-chirpy

lang: ko
timezone: Asia/Seoul

title: hello taeng
tagline: taeng.kim
description: taeng.kim personal blog

url: "https://taengkim.github.io"
baseurl: ""

github:
  username: taengkim

social:
  name: taeng.kim
  email: taeng.kim@kakao.com
  links:
    - https://github.com/taengkim

avatar: ""
toc: true

paginate: 10

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
  - scope:
      path: _tabs
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

plugins:
  - jekyll-feed
